#!/usr/bin/env python
"""
avoid pushing local broken links

Git hooks are by default run from the top-level Git repo directory
"""

import subprocess
import shutil
from pathlib import Path


if not shutil.which("linkcheckMarkdown"):
    raise SystemExit("please install https://github.com/scivision/linkchecker-markdown")

ok = True
for p in ("content", "content/posts"):
    stdout = subprocess.check_output(
        ["linkcheckMarkdown", "-local", p], universal_newlines=True
    )
    if stdout:
        print(stdout)
        ok = False

if not ok:
    raise SystemExit("Fix internal site links.")
