#!/usr/bin/env python3
"""
avoid pushing local broken links.
This example "content/posts" is for Hugo static site generator sites.

Git hooks are by default run from the top-level Git repo directory
"""

import subprocess
import shutil


if not shutil.which("linkcheckMarkdown"):
    raise SystemExit("please install https://github.com/scivision/linkchecker-markdown")

ok = True
for p in ["content/posts"]:
    out = subprocess.check_output(["linkcheckMarkdown", "-local", p], text=True)
    if out:
        print(out)
        ok = False

if not ok:
    raise SystemExit("Fix internal site links.")
